services:
  matlab-head-node:
    image: ghcr.io/wryo813/matlab-parallel-server-full:r2025b
    #build:
    #  context: ..
    #  dockerfile: Dockerfile
    container_name: matlab-head-node
    network_mode: host
    ipc: host
    restart: always
    environment:
      - FQDN=${FQDN:-head.matlab.internal}
      - JM_NAME=${JM_NAME:-MyMJS}
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        
        # MATLABインストールパスの動的取得
        EXISTING_MATLAB_LOCATION=$$(dirname $$(dirname $$(readlink -f $$(which matlab))))
        MJS_DEF_FILE="$${EXISTING_MATLAB_LOCATION}/toolbox/parallel/bin/mjs_def.sh"
        MJS_BIN="$${EXISTING_MATLAB_LOCATION}/toolbox/parallel/bin/mjs"
        START_JOB_MANAGER_BIN="$${EXISTING_MATLAB_LOCATION}/toolbox/parallel/bin/startjobmanager"
        NODESTATUS_BIN="$${EXISTING_MATLAB_LOCATION}/toolbox/parallel/bin/nodestatus"
        
        # FQDNの書き換え処理
        if [ -n "$${FQDN}" ] && [ -f "$${MJS_DEF_FILE}" ]; then
            sed -i 's|^#HOSTNAME=`hostname -f`|HOSTNAME="'"$${FQDN}"'"|' "$${MJS_DEF_FILE}"
        fi
        
        # ジョブマネージャー起動処理をバックグラウンド（サブシェル）で非同期実行
        (
            # エラーによるサブシェルの強制終了を防ぐ
            set +e

            # MJSサービスプロセスがポートのバインド等を完了するためのバッファ時間（sleepさせるのバカすぎるので直したい）
            sleep 10
            
            # ジョブマネージャープロセスの起動
            "$${START_JOB_MANAGER_BIN}" -name "$${JM_NAME}" -clean -v
        ) &
        
        # メインプロセスとして mjs サービスをフォアグラウンドで起動し、PID 1 に置換
        exec "$${MJS_BIN}" console -clean